### ISSUE TITLE
data persistance

### ISSUE THREAD

**Issue by masterdubs** [QuantumObject/docker-odoo#2]
Hi, 
wan we mount volume for data persistance ?

**Comment by angelrr7702** [comment]
Hi, 

 Odoo allow to backup your database .. and you can install update odoo and restore it again and work fine .. but you have to be carefull  that is the same version ... from odoo 8 to odoo 9 you can't export and import .. the last time I try on my site it fail to work but on the same version it work fine .

to access this options at : 

www.yourodoosite.com//web/database/manager#action=database_manager
 
and recommended to used the zip(include filestore) at backup format. 

and few days ago I change from odoo 8 to odoo 9 on my default install for my container .. if you still want to used the old version need to include the tag 8 (docker-odoo:8)

Angel Rodriguez

**Comment by masterdubs** [comment]
Hi, 
Thank you for reply.
A docker container can be started or stopped any time, if you restart your container ( or server need a restart ) the data will be lost.

**Comment by angelrr7702** [comment]
Hi,

 Sorry if you mean ... docker stop and docker start ... that keep the data .. I using odoo on my site for a long time ... www.quantumobject.com  and I keep my server update and reboot it all the time when needed ... and I always able to used docker start to all my container without loosing data .. some time .. the database got some problem for a not clean stop and needed to do small maintenance but I never lose the data at this point ..

for other part if you used _docker run_ each time and maybe you used script to delete the stopped container , that will create a new container and all the old data gone.  in that case , you can fork my container and make the necessary change .. with that you be able to create your own container that will keep data on VOLUME for data persistence.

sincerely
Angel Rodriguez

**Comment by oucart** [comment]
hi , @angelrr7702 
 I run the command
root@vultr:~# docker run -d -p 8069 -p 8070 quantumobject/docker-odoo:9
Unable to find image 'quantumobject/docker-odoo:9' locally
9: Pulling from quantumobject/docker-odoo
61390291298a: Pull complete
f8b51935d699: Pull complete
e4e38c322d0e: Pull complete
9bc927dbaa4c: Pull complete
05c977123e90: Pull complete
0eee7d86c633: Pull complete
f6c7529f8e81: Pull complete
336b85591ace: Pull complete
dd3e714a204f: Pull complete
a050e38b25b0: Pull complete
413901b34713: Pull complete
88a6aa59ec9b: Pull complete
c3e89006ee9a: Pull complete
b5359988b6f7: Pull complete
9c10381a14e9: Pull complete
bf6efa8d727e: Pull complete
c09efb7d2e90: Pull complete
4d18d8e463ac: Pull complete
666e3e88291c: Pull complete
e734a55cbaf1: Pull complete
8f007e93ead8: Pull complete
454da1145e24: Pull complete
Digest: sha256:f1bc49cd1af689ebe55a7e3167f852aee87f98ef291ee1e18a5f6c777e518a04
Status: Downloaded newer image for quantumobject/docker-odoo:9
0a27c1e1e93d142180e8a6f376d6bf570fc56dcbcd9dc90a34da6e435f3ccb54

but ,i don't access my webhost:8069

**Comment by masterdubs** [comment]
Hi @oucart,
your command need to be docker run -d -p 8069:8069 -p 8070:8070 quantumobject/docker-odoo:9
or you need to run docker ps to see the port mapped to 8069.
